

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * 
 */
public class deleteproduct extends javax.swing.JFrame {
 PreparedStatement pstatement;
    ResultSet rset;
    Statement statement;
    /**
     * Creates new form homepage
     */
    private String ro;
    public deleteproduct() {
        initComponents();
    }
    public deleteproduct(String rno) {
        initComponents();
        ro=rno;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backgroundpanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        productBtn = new javax.swing.JButton();
        homeBtn = new javax.swing.JButton();
        flowBtn = new javax.swing.JButton();
        transactionBtn = new javax.swing.JButton();
        changepasswordBtn = new javax.swing.JButton();
        logoutBtn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        productidTxt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        productdeleteBtn = new javax.swing.JButton();
        producteditpageBtn = new javax.swing.JButton();
        resultLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setMaximumSize(new java.awt.Dimension(663, 400));
        setMinimumSize(new java.awt.Dimension(663, 400));

        backgroundpanel.setBackground(new java.awt.Color(255, 255, 255));
        backgroundpanel.setMaximumSize(new java.awt.Dimension(663, 400));
        backgroundpanel.setPreferredSize(new java.awt.Dimension(663, 400));

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        productBtn.setBackground(new java.awt.Color(61, 61, 61));
        productBtn.setFont(new java.awt.Font("Shree Devanagari 714", 1, 12)); // NOI18N
        productBtn.setText("Product");
        productBtn.setBorder(null);
        productBtn.setBorderPainted(false);
        productBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productBtnActionPerformed(evt);
            }
        });

        homeBtn.setBackground(new java.awt.Color(67, 67, 67));
        homeBtn.setFont(new java.awt.Font("Shree Devanagari 714", 1, 12)); // NOI18N
        homeBtn.setText("Home");
        homeBtn.setBorder(null);
        homeBtn.setBorderPainted(false);
        homeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeBtnActionPerformed(evt);
            }
        });

        flowBtn.setBackground(new java.awt.Color(55, 55, 55));
        flowBtn.setFont(new java.awt.Font("Shree Devanagari 714", 1, 12)); // NOI18N
        flowBtn.setText("Inflow/Outflow");
        flowBtn.setBorder(null);
        flowBtn.setBorderPainted(false);
        flowBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                flowBtnActionPerformed(evt);
            }
        });

        transactionBtn.setBackground(new java.awt.Color(53, 53, 53));
        transactionBtn.setFont(new java.awt.Font("Shree Devanagari 714", 1, 12)); // NOI18N
        transactionBtn.setText("Transaction List");
        transactionBtn.setBorder(null);
        transactionBtn.setBorderPainted(false);
        transactionBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transactionBtnActionPerformed(evt);
            }
        });

        changepasswordBtn.setBackground(new java.awt.Color(52, 52, 52));
        changepasswordBtn.setFont(new java.awt.Font("Shree Devanagari 714", 1, 12)); // NOI18N
        changepasswordBtn.setText("Change Password");
        changepasswordBtn.setBorder(null);
        changepasswordBtn.setBorderPainted(false);
        changepasswordBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changepasswordBtnActionPerformed(evt);
            }
        });

        logoutBtn.setBackground(new java.awt.Color(51, 51, 51));
        logoutBtn.setFont(new java.awt.Font("Shree Devanagari 714", 1, 12)); // NOI18N
        logoutBtn.setText("Log Out");
        logoutBtn.setBorder(null);
        logoutBtn.setBorderPainted(false);
        logoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(productBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(homeBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(flowBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(transactionBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(changepasswordBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
            .addComponent(logoutBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(homeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(productBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(flowBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(transactionBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(changepasswordBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(logoutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));

        jLabel1.setFont(new java.awt.Font("Shree Devanagari 714", 0, 24)); // NOI18N
        jLabel1.setText("Delete Product");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(148, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(145, 145, 145))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(28, 28, 28))
        );

        productidTxt.setBackground(new java.awt.Color(255, 255, 255));
        productidTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productidTxtActionPerformed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(51, 51, 51));
        jLabel2.setFont(new java.awt.Font("Shree Devanagari 714", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("Product Id: ");

        productdeleteBtn.setBackground(new java.awt.Color(51, 51, 51));
        productdeleteBtn.setText("Submit");
        productdeleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productdeleteBtnActionPerformed(evt);
            }
        });

        producteditpageBtn.setBackground(new java.awt.Color(153, 153, 153));
        producteditpageBtn.setText("Edit Product");
        producteditpageBtn.setBorderPainted(false);
        producteditpageBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                producteditpageBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout backgroundpanelLayout = new javax.swing.GroupLayout(backgroundpanel);
        backgroundpanel.setLayout(backgroundpanelLayout);
        backgroundpanelLayout.setHorizontalGroup(
            backgroundpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundpanelLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(backgroundpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(backgroundpanelLayout.createSequentialGroup()
                        .addGroup(backgroundpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(backgroundpanelLayout.createSequentialGroup()
                                .addGap(138, 138, 138)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(productidTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(backgroundpanelLayout.createSequentialGroup()
                                .addGap(173, 173, 173)
                                .addComponent(productdeleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(backgroundpanelLayout.createSequentialGroup()
                                .addGap(159, 159, 159)
                                .addComponent(producteditpageBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(backgroundpanelLayout.createSequentialGroup()
                                .addGap(78, 78, 78)
                                .addComponent(resultLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundpanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, 0))
        );
        backgroundpanelLayout.setVerticalGroup(
            backgroundpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(backgroundpanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(resultLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(backgroundpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(productidTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(38, 38, 38)
                .addComponent(productdeleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(producteditpageBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(59, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        backgroundpanel.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void productdeleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productdeleteBtnActionPerformed
        // TODO add your handling code here:
       String productid = productidTxt.getText();
       // checks if productid is only numeric and has atleast one integer.
          if(productid.length()>0 && productid.matches("[0-9]+")){
        try {
            // establish connection with MySQL database
            Class.forName("com.mysql.cj.jdbc.Driver");
            String url="jdbc:mysql://localhost:3306/resourceinventorymanagement";
            Connection con=DriverManager.getConnection(url,"root","Hari2006");
            String sql = "SELECT * FROM product_table;";
            pstatement = con.prepareStatement(sql);
            rset = pstatement.executeQuery();
            // query executed
             while(rset.next()){
               String id = rset.getString("productid");
               if (productid.equals(id)){
                   statement=con.createStatement();
                   // deletes product with the product id if the product id exists in the database
                   String delete = "delete from product_table where productid='"+productid+"';";
                   statement.executeUpdate(delete);
                   
                   new product(ro).setVisible(true);
                setVisible(false);
                // alerts the user
                JOptionPane.showMessageDialog(null,"Product Deleted!");
                StreamlinerLog.init();
                                  // logs info in the Streamlinerlog. 
            StreamlinerLog.logger.info("Product ID: "+productid+" is deleted by "+ro);
                   
               }
               else{
                 resultLbl.setText("Please enter an existing ProductID");
               }
               }
             
    }                       // catch clause for MySQL and class error. logs errors as well                              
catch (SQLException e) {
            JOptionPane.showMessageDialog(null,"Oops!, Something went wrong. Please Restart the Application and try again. Error: Unable to establish connection to database.");
             StreamlinerLog.init();
            StreamlinerLog.logger.severe("Exception :: "+e);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null,"Oops!, Something went wrong. Please Restart the Application and try again. Error: Unable to utilise JDBC Driver.");
             StreamlinerLog.init();
            StreamlinerLog.logger.severe("Exception :: "+ex);
        }} else{
              resultLbl.setText("Please enter a numeric ProductID");
          }
    
    }//GEN-LAST:event_productdeleteBtnActionPerformed

    private void productidTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productidTxtActionPerformed
        // TODO add your handling code here:
        new product(ro).setVisible(true);
                setVisible(false);
    }//GEN-LAST:event_productidTxtActionPerformed

    private void changepasswordBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changepasswordBtnActionPerformed
        // TODO add your handling code here:
                new changepassword(ro).setVisible(true);
                setVisible(false);
    }//GEN-LAST:event_changepasswordBtnActionPerformed

    private void transactionBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transactionBtnActionPerformed
        // TODO add your handling code here:
           new transactionlist(ro).setVisible(true);
                setVisible(false);
    }//GEN-LAST:event_transactionBtnActionPerformed

    private void flowBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_flowBtnActionPerformed
        // TODO add your handling code here:
             new flowtransaction(ro).setVisible(true);
                setVisible(false);
    }//GEN-LAST:event_flowBtnActionPerformed

    private void homeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeBtnActionPerformed
        // TODO add your handling code here:
         new home(ro).setVisible(true);
                setVisible(false);
    }//GEN-LAST:event_homeBtnActionPerformed

    private void logoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBtnActionPerformed
        // TODO add your handling code here:
                 new login().setVisible(true);
                setVisible(false);
                 StreamlinerLog.init();
            StreamlinerLog.logger.info("Admin ID: "+ro+" has logged out.");
    }//GEN-LAST:event_logoutBtnActionPerformed

    private void productBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productBtnActionPerformed
        // TODO add your handling code here:
         new product(ro).setVisible(true);
                setVisible(false);
    }//GEN-LAST:event_productBtnActionPerformed

    private void producteditpageBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_producteditpageBtnActionPerformed
        // TODO add your handling code here:
         new editproduct(ro).setVisible(true);
                setVisible(false);
    }//GEN-LAST:event_producteditpageBtnActionPerformed
                                 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel backgroundpanel;
    private javax.swing.JButton changepasswordBtn;
    private javax.swing.JButton flowBtn;
    private javax.swing.JButton homeBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton logoutBtn;
    private javax.swing.JButton productBtn;
    private javax.swing.JButton productdeleteBtn;
    private javax.swing.JButton producteditpageBtn;
    private javax.swing.JTextField productidTxt;
    private javax.swing.JLabel resultLbl;
    private javax.swing.JButton transactionBtn;
    // End of variables declaration//GEN-END:variables
}
