
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * 
 */
public class edittransaction extends javax.swing.JFrame {
PreparedStatement pstatement,productpstatement;
    ResultSet rset,productrset;
    Statement statement;
    private String ro;
    /**
     * Creates new form homepage
     */
    public edittransaction(String rno) {
        initComponents();
        ro=rno;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        transactionflowBtn = new javax.swing.ButtonGroup();
        backgroundpanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        productBtn = new javax.swing.JButton();
        homeBtn = new javax.swing.JButton();
        flowBtn = new javax.swing.JButton();
        transactionBtn = new javax.swing.JButton();
        changepasswordBtn = new javax.swing.JButton();
        logoutBtn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        productidTxt = new javax.swing.JTextField();
        quantityTxt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        transactioneditBtn = new javax.swing.JButton();
        outflowBtn = new javax.swing.JRadioButton();
        inflowBtn = new javax.swing.JRadioButton();
        transactiondeletepageBtn = new javax.swing.JButton();
        transactionidTxt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        resultLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setMaximumSize(new java.awt.Dimension(663, 403));
        setMinimumSize(new java.awt.Dimension(663, 403));
        setSize(new java.awt.Dimension(663, 403));

        backgroundpanel.setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        productBtn.setBackground(new java.awt.Color(61, 61, 61));
        productBtn.setFont(new java.awt.Font("Shree Devanagari 714", 1, 12)); // NOI18N
        productBtn.setText("Product");
        productBtn.setBorder(null);
        productBtn.setBorderPainted(false);
        productBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productBtnActionPerformed(evt);
            }
        });

        homeBtn.setBackground(new java.awt.Color(67, 67, 67));
        homeBtn.setFont(new java.awt.Font("Shree Devanagari 714", 1, 12)); // NOI18N
        homeBtn.setText("Home");
        homeBtn.setBorder(null);
        homeBtn.setBorderPainted(false);
        homeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeBtnActionPerformed(evt);
            }
        });

        flowBtn.setBackground(new java.awt.Color(55, 55, 55));
        flowBtn.setFont(new java.awt.Font("Shree Devanagari 714", 1, 12)); // NOI18N
        flowBtn.setText("Inflow/Outflow");
        flowBtn.setBorder(null);
        flowBtn.setBorderPainted(false);
        flowBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                flowBtnActionPerformed(evt);
            }
        });

        transactionBtn.setBackground(new java.awt.Color(53, 53, 53));
        transactionBtn.setFont(new java.awt.Font("Shree Devanagari 714", 1, 12)); // NOI18N
        transactionBtn.setText("Transaction List");
        transactionBtn.setBorder(null);
        transactionBtn.setBorderPainted(false);
        transactionBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transactionBtnActionPerformed(evt);
            }
        });

        changepasswordBtn.setBackground(new java.awt.Color(52, 52, 52));
        changepasswordBtn.setFont(new java.awt.Font("Shree Devanagari 714", 1, 12)); // NOI18N
        changepasswordBtn.setText("Change Password");
        changepasswordBtn.setBorder(null);
        changepasswordBtn.setBorderPainted(false);
        changepasswordBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changepasswordBtnActionPerformed(evt);
            }
        });

        logoutBtn.setBackground(new java.awt.Color(51, 51, 51));
        logoutBtn.setFont(new java.awt.Font("Shree Devanagari 714", 1, 12)); // NOI18N
        logoutBtn.setText("Log Out");
        logoutBtn.setBorder(null);
        logoutBtn.setBorderPainted(false);
        logoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(productBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(homeBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(flowBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(transactionBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(changepasswordBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
            .addComponent(logoutBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(homeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(productBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(flowBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(transactionBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(changepasswordBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(logoutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));

        jLabel1.setFont(new java.awt.Font("Shree Devanagari 714", 0, 24)); // NOI18N
        jLabel1.setText("Edit/Delete Transaction");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(105, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(95, 95, 95))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(28, 28, 28))
        );

        productidTxt.setBackground(new java.awt.Color(255, 255, 255));
        productidTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productidTxtActionPerformed(evt);
            }
        });

        quantityTxt.setBackground(new java.awt.Color(255, 255, 255));
        quantityTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quantityTxtActionPerformed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(51, 51, 51));
        jLabel2.setFont(new java.awt.Font("Shree Devanagari 714", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("Product Id: ");

        jLabel3.setBackground(new java.awt.Color(51, 51, 51));
        jLabel3.setFont(new java.awt.Font("Shree Devanagari 714", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("Quantity:");

        transactioneditBtn.setBackground(new java.awt.Color(51, 51, 51));
        transactioneditBtn.setFont(new java.awt.Font("Shree Devanagari 714", 0, 13)); // NOI18N
        transactioneditBtn.setText("Edit");
        transactioneditBtn.setBorderPainted(false);
        transactioneditBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transactioneditBtnActionPerformed(evt);
            }
        });

        transactionflowBtn.add(outflowBtn);
        outflowBtn.setFont(new java.awt.Font("Shree Devanagari 714", 0, 13)); // NOI18N
        outflowBtn.setForeground(new java.awt.Color(0, 0, 0));
        outflowBtn.setText("Outflow");
        outflowBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                outflowBtnActionPerformed(evt);
            }
        });

        transactionflowBtn.add(inflowBtn);
        inflowBtn.setFont(new java.awt.Font("Shree Devanagari 714", 0, 13)); // NOI18N
        inflowBtn.setForeground(new java.awt.Color(0, 0, 0));
        inflowBtn.setText("Inflow");

        transactiondeletepageBtn.setBackground(new java.awt.Color(51, 51, 51));
        transactiondeletepageBtn.setFont(new java.awt.Font("Shree Devanagari 714", 0, 13)); // NOI18N
        transactiondeletepageBtn.setText("Delete");
        transactiondeletepageBtn.setBorderPainted(false);
        transactiondeletepageBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transactiondeletepageBtnActionPerformed(evt);
            }
        });

        transactionidTxt.setBackground(new java.awt.Color(255, 255, 255));
        transactionidTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transactionidTxtActionPerformed(evt);
            }
        });

        jLabel4.setBackground(new java.awt.Color(51, 51, 51));
        jLabel4.setFont(new java.awt.Font("Shree Devanagari 714", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("Transaction Id: ");

        javax.swing.GroupLayout backgroundpanelLayout = new javax.swing.GroupLayout(backgroundpanel);
        backgroundpanel.setLayout(backgroundpanelLayout);
        backgroundpanelLayout.setHorizontalGroup(
            backgroundpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundpanelLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(backgroundpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(backgroundpanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundpanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(backgroundpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(backgroundpanelLayout.createSequentialGroup()
                                .addGroup(backgroundpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundpanelLayout.createSequentialGroup()
                                        .addComponent(transactioneditBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(17, 17, 17))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundpanelLayout.createSequentialGroup()
                                        .addGroup(backgroundpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundpanelLayout.createSequentialGroup()
                                                .addComponent(inflowBtn)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel3))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundpanelLayout.createSequentialGroup()
                                                .addComponent(outflowBtn)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(backgroundpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                                .addGroup(backgroundpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(quantityTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(productidTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(transactiondeletepageBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(transactionidTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(resultLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(112, 112, 112))))
        );
        backgroundpanelLayout.setVerticalGroup(
            backgroundpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(backgroundpanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(backgroundpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(backgroundpanelLayout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(backgroundpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(transactionidTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(backgroundpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(productidTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(backgroundpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(quantityTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)))
                    .addGroup(backgroundpanelLayout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(outflowBtn)
                        .addGap(18, 18, 18)
                        .addComponent(inflowBtn)))
                .addGap(18, 18, 18)
                .addGroup(backgroundpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(transactioneditBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(transactiondeletepageBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(resultLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundpanel, javax.swing.GroupLayout.PREFERRED_SIZE, 663, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void changepasswordBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changepasswordBtnActionPerformed
        // TODO add your handling code here:
                    new changepassword(ro).setVisible(true);
                setVisible(false);
    }//GEN-LAST:event_changepasswordBtnActionPerformed

    private void transactionBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transactionBtnActionPerformed
        // TODO add your handling code here:
                    new transactionlist(ro).setVisible(true);
                setVisible(false);
    }//GEN-LAST:event_transactionBtnActionPerformed

    private void flowBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_flowBtnActionPerformed
        // TODO add your handling code here:
                    new flowtransaction(ro).setVisible(true);
                setVisible(false);
    }//GEN-LAST:event_flowBtnActionPerformed

    private void homeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeBtnActionPerformed
        // TODO add your handling code here:
                    new home(ro).setVisible(true);
                setVisible(false);
    }//GEN-LAST:event_homeBtnActionPerformed

    private void productidTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productidTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_productidTxtActionPerformed

    private void quantityTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quantityTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quantityTxtActionPerformed

    private void transactioneditBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transactioneditBtnActionPerformed
        // TODO add your handling code here:
        String tranid = transactionidTxt.getText();
        String productid = productidTxt.getText();
         String qty = quantityTxt.getText();
         Integer count = 0;
         // checks if quantity entered is numeric
         if(qty.matches("[0-9]+")){
         Integer quantity = Integer.parseInt(qty);
           if(quantity>0){
        
        try {
            // establish MySQL connection
            Class.forName("com.mysql.cj.jdbc.Driver");
            String url="jdbc:mysql://localhost:3306/resourceinventorymanagement";
            Connection con=DriverManager.getConnection(url,"root","Hari2006");
           
             String retrieve = "SELECT * FROM transactions_table WHERE transactionsid='"+tranid+"';";
            pstatement = con.prepareStatement(retrieve);
            rset = pstatement.executeQuery();
              
            if (rset.next()){
                String id = rset.getString("transactionsid");
                String prodid=rset.getString("productid");
                String oldqty = rset.getString("quantity");
                String transactiontype = rset.getString("transactiontype");
                Integer oldquantity = Integer.parseInt(oldqty);
                 String get= "SELECT * FROM product_table WHERE productid='"+prodid+"';";
                  productpstatement = con.prepareStatement(get);
            productrset = productpstatement.executeQuery();
            if(productrset.next()){
                // resets quantity to what it would be before the transaction. 
                                String reverseqty = productrset.getString("quantity");
                                String initprodid= productrset.getString("productid");
                Integer reversequantity = Integer.parseInt(reverseqty);
           
            Integer addresetquantity = reversequantity+oldquantity;

            Integer subresetquantity = reversequantity-oldquantity;
            if(productid.equals(initprodid)){
                count=1;
            }
// checks if transaction to be edited is outflow or inflow and sends respective query to the database.
            if (transactiontype.equals("O")){
                String addrevert = "UPDATE product_table SET quantity='"+addresetquantity+"'WHERE productid='"+prodid+"';";
            statement = con.createStatement();
            statement.executeUpdate(addrevert);}
            else{
                String subrevert = "UPDATE product_table SET quantity='"+subresetquantity+"'WHERE productid='"+prodid+"';";
                statement = con.createStatement();
            statement.executeUpdate(subrevert);
            }      
            
                 
                
            // takes new values of the transaction entered by the user and commits actions.
 String get1= "SELECT * FROM product_table WHERE productid='"+productid+"';";
productpstatement = con.prepareStatement(get1);
            productrset = productpstatement.executeQuery();
            if (productrset.next()) {
                String iniqty=productrset.getString("quantity");
                String productname=productrset.getString("productname");
                Integer initialqty= Integer.parseInt(iniqty);
                Integer finaladdqty = quantity+initialqty;
                Integer finalsubqty = initialqty-quantity;
                // when product is sold
                if (outflowBtn.isSelected()){
                    if(finalsubqty>=0){
                        String add = "UPDATE product_table SET quantity='"+finalsubqty+"'WHERE productid='"+productid+"'";
                    statement=con.createStatement();
               statement.executeUpdate(add);
               String transaction = "UPDATE transactions_table SET productid='"+productid+"',productname='"+productname+"',quantity='"+quantity+"',transactiontype='"+"O"+"' WHERE transactionsid='"+tranid+"';";
               statement=con.createStatement();
               statement.executeUpdate(transaction);
               JOptionPane.showMessageDialog(null,"Transaction Edited!");
               StreamlinerLog.init();
               // logs info
            StreamlinerLog.logger.info("Transaction no: "+id+" edited by AdminID: "+ro);
                       new transactionlist(ro).setVisible(true);
                setVisible(false);
                        
                    }
                     else{
                        resultLbl.setText("There is not enough quantity of the product to sell.");
                                   if(count==1){
                                       
                                        String returnback = "UPDATE product_table SET quantity='"+reversequantity+"'WHERE productid='"+prodid+"';";
            statement = con.createStatement();
            statement.executeUpdate(returnback);
               
           }
                    }
                }
                // when product is restocked
                else if(inflowBtn.isSelected()){
                String add = "UPDATE product_table SET quantity='"+finaladdqty+"'WHERE productid='"+productid+"'";
                statement=con.createStatement();
               statement.executeUpdate(add);
                String transaction = "UPDATE transactions_table SET productid='"+productid+"',productname='"+productname+"',quantity='"+quantity+"',transactiontype='"+"I"+"' WHERE transactionsid='"+tranid+"';";
               statement=con.createStatement();
               statement.executeUpdate(transaction);
               JOptionPane.showMessageDialog(null,"Transaction Edited!");
               StreamlinerLog.init();
               // logs info
            StreamlinerLog.logger.info("Transaction no: "+id+" edited by AdminID: "+ro);
                       new transactionlist(ro).setVisible(true);
                setVisible(false);
            }
                else{
                    resultLbl.setText("Please select a radio button to process the transaction");
                }
                
               
            }
            
                   
             
            
                
else{ resultLbl.setText("Please Enter Valid ProductID");
                } 
                              
            } }else{
                      resultLbl.setText("Please Enter Valid TransactionID");} }    
         // catch clause for MySQL and class error. logs errors as well
catch (SQLException e) {
            JOptionPane.showMessageDialog(null,"Oops!, Something went wrong. Please Restart the Application and try again. Error: Unable to establish connection to database.");
            StreamlinerLog.init();
            StreamlinerLog.logger.severe("Exception :: "+e);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null,"Oops!, Something went wrong. Please Restart the Application and try again. Error: Unable to utilise JDBC Driver.");
            StreamlinerLog.init();
            StreamlinerLog.logger.severe("Exception :: "+ex);
        }
           }else{
             resultLbl.setText("Please Enter a Valid Quantity");
         }}else{
             resultLbl.setText("Please Enter Numeric Quantity");
         }
            
    }//GEN-LAST:event_transactioneditBtnActionPerformed

    private void outflowBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_outflowBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_outflowBtnActionPerformed

    private void transactiondeletepageBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transactiondeletepageBtnActionPerformed
        // TODO add your handling code here:
        new deletetransaction(ro).setVisible(true);
                setVisible(false);
    }//GEN-LAST:event_transactiondeletepageBtnActionPerformed

    private void productBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productBtnActionPerformed
        // TODO add your handling code here:
                    new product(ro).setVisible(true);
                setVisible(false);
    }//GEN-LAST:event_productBtnActionPerformed

    private void logoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBtnActionPerformed
        // TODO add your handling code here:
                    new login().setVisible(true);
                setVisible(false);
                 StreamlinerLog.init();
            StreamlinerLog.logger.info("Admin ID: "+ro+" has logged out.");
    }//GEN-LAST:event_logoutBtnActionPerformed

    private void transactionidTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transactionidTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_transactionidTxtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel backgroundpanel;
    private javax.swing.JButton changepasswordBtn;
    private javax.swing.JButton flowBtn;
    private javax.swing.JButton homeBtn;
    private javax.swing.JRadioButton inflowBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton logoutBtn;
    private javax.swing.JRadioButton outflowBtn;
    private javax.swing.JButton productBtn;
    private javax.swing.JTextField productidTxt;
    private javax.swing.JTextField quantityTxt;
    private javax.swing.JLabel resultLbl;
    private javax.swing.JButton transactionBtn;
    private javax.swing.JButton transactiondeletepageBtn;
    private javax.swing.JButton transactioneditBtn;
    private javax.swing.ButtonGroup transactionflowBtn;
    private javax.swing.JTextField transactionidTxt;
    // End of variables declaration//GEN-END:variables
}
