/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import java.text.SimpleDateFormat;  
import java.util.Date;  
/**
 *
 
 */
public class flowtransaction extends javax.swing.JFrame {
PreparedStatement pstatement;
    ResultSet rset;
    Statement statement;
    /**
     * Creates new form homepage
     */
    private String ro;
    public flowtransaction(String rno) {
        ro = rno;
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        transactionflowBtn = new javax.swing.ButtonGroup();
        backgroundpanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        productBtn = new javax.swing.JButton();
        homeBtn = new javax.swing.JButton();
        flowBtn = new javax.swing.JButton();
        transactionBtn = new javax.swing.JButton();
        changepasswordBtn = new javax.swing.JButton();
        logoutBtn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        productidTxt = new javax.swing.JTextField();
        quantityTxt = new javax.swing.JTextField();
        resultLbl = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        transactionsubmitBtn = new javax.swing.JButton();
        outflowBtn = new javax.swing.JRadioButton();
        inflowBtn = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setMaximumSize(new java.awt.Dimension(665, 400));
        setMinimumSize(new java.awt.Dimension(665, 400));

        backgroundpanel.setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        productBtn.setBackground(new java.awt.Color(61, 61, 61));
        productBtn.setFont(new java.awt.Font("Shree Devanagari 714", 1, 12)); // NOI18N
        productBtn.setText("Product");
        productBtn.setBorder(null);
        productBtn.setBorderPainted(false);
        productBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productBtnActionPerformed(evt);
            }
        });

        homeBtn.setBackground(new java.awt.Color(67, 67, 67));
        homeBtn.setFont(new java.awt.Font("Shree Devanagari 714", 1, 12)); // NOI18N
        homeBtn.setText("Home");
        homeBtn.setBorder(null);
        homeBtn.setBorderPainted(false);
        homeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeBtnActionPerformed(evt);
            }
        });

        flowBtn.setBackground(new java.awt.Color(55, 55, 55));
        flowBtn.setFont(new java.awt.Font("Shree Devanagari 714", 1, 12)); // NOI18N
        flowBtn.setText("Inflow/Outflow");
        flowBtn.setBorder(null);
        flowBtn.setBorderPainted(false);
        flowBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                flowBtnActionPerformed(evt);
            }
        });

        transactionBtn.setBackground(new java.awt.Color(53, 53, 53));
        transactionBtn.setFont(new java.awt.Font("Shree Devanagari 714", 1, 12)); // NOI18N
        transactionBtn.setText("Transaction List");
        transactionBtn.setBorder(null);
        transactionBtn.setBorderPainted(false);
        transactionBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transactionBtnActionPerformed(evt);
            }
        });

        changepasswordBtn.setBackground(new java.awt.Color(52, 52, 52));
        changepasswordBtn.setFont(new java.awt.Font("Shree Devanagari 714", 1, 12)); // NOI18N
        changepasswordBtn.setText("Change Password");
        changepasswordBtn.setBorder(null);
        changepasswordBtn.setBorderPainted(false);
        changepasswordBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changepasswordBtnActionPerformed(evt);
            }
        });

        logoutBtn.setBackground(new java.awt.Color(51, 51, 51));
        logoutBtn.setFont(new java.awt.Font("Shree Devanagari 714", 1, 12)); // NOI18N
        logoutBtn.setText("Log Out");
        logoutBtn.setBorder(null);
        logoutBtn.setBorderPainted(false);
        logoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(productBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(homeBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(flowBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(transactionBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(changepasswordBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
            .addComponent(logoutBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(homeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(productBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(flowBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(transactionBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(changepasswordBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(logoutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));

        jLabel1.setFont(new java.awt.Font("Shree Devanagari 714", 0, 24)); // NOI18N
        jLabel1.setText("Add Transaction");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(jLabel1)
                .addContainerGap(69, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(26, 26, 26))
        );

        productidTxt.setBackground(new java.awt.Color(255, 255, 255));
        productidTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productidTxtActionPerformed(evt);
            }
        });

        quantityTxt.setBackground(new java.awt.Color(255, 255, 255));
        quantityTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quantityTxtActionPerformed(evt);
            }
        });

        resultLbl.setBackground(new java.awt.Color(51, 51, 51));
        resultLbl.setFont(new java.awt.Font("Shree Devanagari 714", 0, 12)); // NOI18N
        resultLbl.setForeground(new java.awt.Color(51, 51, 51));

        jLabel3.setBackground(new java.awt.Color(51, 51, 51));
        jLabel3.setFont(new java.awt.Font("Shree Devanagari 714", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("Quantity:");

        transactionsubmitBtn.setBackground(new java.awt.Color(51, 51, 51));
        transactionsubmitBtn.setFont(new java.awt.Font("Shree Devanagari 714", 0, 13)); // NOI18N
        transactionsubmitBtn.setText("Submit");
        transactionsubmitBtn.setBorderPainted(false);
        transactionsubmitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transactionsubmitBtnActionPerformed(evt);
            }
        });

        transactionflowBtn.add(outflowBtn);
        outflowBtn.setFont(new java.awt.Font("Shree Devanagari 714", 0, 13)); // NOI18N
        outflowBtn.setForeground(new java.awt.Color(0, 0, 0));
        outflowBtn.setText("Outflow");
        outflowBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                outflowBtnActionPerformed(evt);
            }
        });

        transactionflowBtn.add(inflowBtn);
        inflowBtn.setFont(new java.awt.Font("Shree Devanagari 714", 0, 13)); // NOI18N
        inflowBtn.setForeground(new java.awt.Color(0, 0, 0));
        inflowBtn.setText("Inflow");

        jLabel4.setBackground(new java.awt.Color(51, 51, 51));
        jLabel4.setFont(new java.awt.Font("Shree Devanagari 714", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("Product Id: ");

        javax.swing.GroupLayout backgroundpanelLayout = new javax.swing.GroupLayout(backgroundpanel);
        backgroundpanel.setLayout(backgroundpanelLayout);
        backgroundpanelLayout.setHorizontalGroup(
            backgroundpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundpanelLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(backgroundpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundpanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(backgroundpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(backgroundpanelLayout.createSequentialGroup()
                                .addComponent(inflowBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(quantityTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(backgroundpanelLayout.createSequentialGroup()
                                .addComponent(outflowBtn)
                                .addGap(44, 44, 44)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(productidTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(75, 75, 75))
                    .addGroup(backgroundpanelLayout.createSequentialGroup()
                        .addGroup(backgroundpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(backgroundpanelLayout.createSequentialGroup()
                                .addGap(188, 188, 188)
                                .addComponent(transactionsubmitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(backgroundpanelLayout.createSequentialGroup()
                                .addGap(64, 64, 64)
                                .addGroup(backgroundpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(resultLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(52, Short.MAX_VALUE))))
        );
        backgroundpanelLayout.setVerticalGroup(
            backgroundpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(backgroundpanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(resultLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(backgroundpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(productidTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(outflowBtn)
                    .addComponent(jLabel4))
                .addGap(29, 29, 29)
                .addGroup(backgroundpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(quantityTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inflowBtn))
                .addGap(38, 38, 38)
                .addComponent(transactionsubmitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(58, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void changepasswordBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changepasswordBtnActionPerformed
        // TODO add your handling code here:
                    new changepassword(ro).setVisible(true);
                setVisible(false);
    }//GEN-LAST:event_changepasswordBtnActionPerformed

    private void transactionBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transactionBtnActionPerformed
        // TODO add your handling code here:
                    new transactionlist(ro).setVisible(true);
                setVisible(false);
    }//GEN-LAST:event_transactionBtnActionPerformed

    private void flowBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_flowBtnActionPerformed
        // TODO add your handling code here:
                    new flowtransaction(ro).setVisible(true);
                setVisible(false);
    }//GEN-LAST:event_flowBtnActionPerformed

    private void homeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeBtnActionPerformed
        // TODO add your handling code here:
                    new home(ro).setVisible(true);
                setVisible(false);
    }//GEN-LAST:event_homeBtnActionPerformed

    private void productidTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productidTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_productidTxtActionPerformed

    private void quantityTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quantityTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quantityTxtActionPerformed

    private void transactionsubmitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transactionsubmitBtnActionPerformed
        // TODO add your handling code here:
        // clears the alert label in case of a new transaction being added right after.
        resultLbl.setText("");
         String productid = productidTxt.getText();
         String qty = quantityTxt.getText();
         // acquires date and time of the transaction
                          SimpleDateFormat formatter = new SimpleDateFormat("dd/MM/yyyy HH:mm:ss");
                              Date date = new Date();  
                             String transactiondate = formatter.format(date);
                             // checks if quantity and product id is only numeric
if(qty.matches("[0-9]+")){
   if (productid.matches("[0-9]+")){
         Integer quantity = Integer.parseInt(qty);
                  if(quantity>0){

        try {
            // establishes connection to MySQL
            Class.forName("com.mysql.cj.jdbc.Driver");
            String url="jdbc:mysql://localhost:3306/resourceinventorymanagement";
            Connection con=DriverManager.getConnection(url,"root","Hari2006");
            String get= "SELECT * FROM product_table WHERE productid='"+productid+"';";
               pstatement = con.prepareStatement(get);
            rset = pstatement.executeQuery();

            if (rset.next()) {
                resultLbl.setText("");
                String iniqty=rset.getString("quantity");
                String productname=rset.getString("productname");
                // acquires information of the quantity entered and calculates new quantity for the product depending on the radio button chosen
                Integer initialqty= Integer.parseInt(iniqty);
                Integer finaladdqty = quantity+initialqty;
                Integer finalsubqty = initialqty-quantity;
  
                if (outflowBtn.isSelected()){     
                    if(finalsubqty<=0){
                        resultLbl.setText("There is not enough quantity of the product to sell.");
                        return;
                    }
                     else{
                        // when a quantity of product is sold.
                    String add = "UPDATE product_table SET quantity='"+finalsubqty+"'WHERE productid='"+productid+"'";
                    statement=con.createStatement();
               statement.executeUpdate(add);
               String transaction = "insert into transactions_table (productid,productname,quantity,transactiondate,transactiontype) values('"+productid+"','"+productname+"','"+quantity+"','"+transactiondate+"','"+"O"+"');";
               statement=con.createStatement();
               statement.executeUpdate(transaction);
                    JOptionPane.showMessageDialog(null,"Transaction Processed!");
                    StreamlinerLog.init();
                    // logs info.
            StreamlinerLog.logger.info("Transaction processed by AdminID: "+ro);
                    productidTxt.setText("");
        quantityTxt.setText("");}
                }
                else if(inflowBtn.isSelected()){
                    // when quantity of a product is restocked
                String add = "UPDATE product_table SET quantity='"+finaladdqty+"'WHERE productid='"+productid+"'";
                statement=con.createStatement();
               statement.executeUpdate(add);
                String transaction = "insert into transactions_table (productid,productname,quantity,transactiondate,transactiontype) values('"+productid+"','"+productname+"','"+quantity+"','"+transactiondate+"','"+"I"+"');";
               statement=con.createStatement();
               statement.executeUpdate(transaction);
               
                JOptionPane.showMessageDialog(null,"Transaction Processed!");
                 StreamlinerLog.init();
                 // logs info.
            StreamlinerLog.logger.info("Transaction processed by AdminID: "+ro);
                statement.close();

                productidTxt.setText("");
        quantityTxt.setText("");
            }
                else{
             resultLbl.setText("Please select the flow button to process the transaction");
                }
                
               
            }
            

else{
    resultLbl.setText("Invalid ProductID entered");
}
                       con.close();
              
    }                   // catch clause for MySQL and class error. logs errors as well                            
catch (SQLException e) {
            JOptionPane.showMessageDialog(null,"Oops!, Something went wrong. Please Restart the Application and try again. Error: Unable to establish connection to database.");
            StreamlinerLog.init();
            StreamlinerLog.logger.severe("Exception :: "+e);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
             JOptionPane.showMessageDialog(null,"Oops!, Something went wrong. Please Restart the Application and try again. Error: Unable to utilise JDBC driver.");
             StreamlinerLog.init();
            StreamlinerLog.logger.severe("Exception :: "+ex);
        }
                  }
                  else{
                      resultLbl.setText("Please enter a valid quantity");
                  }
                  }else{
       resultLbl.setText("Please enter numeric values for Quantity & ProductID");
   }}
else{
    resultLbl.setText("Please enter numeric values for Quantity & ProductID");
}
    }//GEN-LAST:event_transactionsubmitBtnActionPerformed

    private void outflowBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_outflowBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_outflowBtnActionPerformed

    private void productBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productBtnActionPerformed
        // TODO add your handling code here:
                    new product(ro).setVisible(true);
                setVisible(false);
    }//GEN-LAST:event_productBtnActionPerformed

    private void logoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBtnActionPerformed
        // TODO add your handling code here:
                    new login().setVisible(true);
                setVisible(false);
                 StreamlinerLog.init();
            StreamlinerLog.logger.info("Admin ID: "+ro+" has logged out.");
    }//GEN-LAST:event_logoutBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel backgroundpanel;
    private javax.swing.JButton changepasswordBtn;
    private javax.swing.JButton flowBtn;
    private javax.swing.JButton homeBtn;
    private javax.swing.JRadioButton inflowBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton logoutBtn;
    private javax.swing.JRadioButton outflowBtn;
    private javax.swing.JButton productBtn;
    private javax.swing.JTextField productidTxt;
    private javax.swing.JTextField quantityTxt;
    private javax.swing.JLabel resultLbl;
    private javax.swing.JButton transactionBtn;
    private javax.swing.ButtonGroup transactionflowBtn;
    private javax.swing.JButton transactionsubmitBtn;
    // End of variables declaration//GEN-END:variables
}
