/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * 
 */
import java.awt.Color;
import java.sql.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JFrame;
import java.text.SimpleDateFormat;  
import java.util.Date;  
import javax.mail.MessagingException;

public class login extends javax.swing.JFrame {
    
    PreparedStatement pstatement;
    Statement statement;
    ResultSet rset;
    Integer attempt = 0;
    
    /**
     * Creates new form login
     */
    public login() {
        initComponents();    
        
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        nameTxt = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        loginBtn = new javax.swing.JButton();
        resultLbl = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        forgotpasswordBtn = new javax.swing.JButton();
        passwordTxt = new javax.swing.JPasswordField();
        registerBtn = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMaximumSize(new java.awt.Dimension(660, 401));
        setMinimumSize(new java.awt.Dimension(660, 401));
        setSize(new java.awt.Dimension(660, 401));

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Shree Devanagari 714", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Interface!");

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setFont(new java.awt.Font("Shree Devanagari 714", 0, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Welcome to the");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(41, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(35, 35, 35))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(83, 83, 83))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(128, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(163, 163, 163))
        );

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));
        jPanel2.setForeground(new java.awt.Color(186, 79, 84));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nameTxt.setBackground(new java.awt.Color(153, 153, 153));
        nameTxt.setFont(new java.awt.Font("Shree Devanagari 714", 0, 13)); // NOI18N
        nameTxt.setForeground(new java.awt.Color(204, 204, 204));
        nameTxt.setToolTipText("");
        nameTxt.setBorder(null);
        nameTxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nameTxtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                nameTxtFocusLost(evt);
            }
        });
        nameTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTxtActionPerformed(evt);
            }
        });
        jPanel2.add(nameTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, 190, -1));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, -1, -1));

        jSeparator2.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, 190, 20));

        jSeparator3.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator3.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, 190, 20));

        jLabel4.setBackground(new java.awt.Color(153, 153, 153));
        jLabel4.setFont(new java.awt.Font("Shree Devanagari 714", 0, 13)); // NOI18N
        jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, 90, 30));

        loginBtn.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.disabledBackground"));
        loginBtn.setFont(new java.awt.Font("Shree Devanagari 714", 0, 13)); // NOI18N
        loginBtn.setForeground(new java.awt.Color(0, 0, 0));
        loginBtn.setText("Login");
        loginBtn.setToolTipText("");
        loginBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        loginBtn.setBorderPainted(false);
        loginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBtnActionPerformed(evt);
            }
        });
        jPanel2.add(loginBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, 90, 30));
        jPanel2.add(resultLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 300, 30));

        jLabel6.setBackground(new java.awt.Color(0, 0, 0));
        jLabel6.setFont(new java.awt.Font("Shree Devanagari 714", 0, 14)); // NOI18N
        jLabel6.setText("Forgot Password?");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, -1, 30));

        jLabel7.setBackground(new java.awt.Color(0, 0, 0));
        jLabel7.setFont(new java.awt.Font("Shree Devanagari 714", 0, 24)); // NOI18N
        jLabel7.setText("Login");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, -1, 52));

        forgotpasswordBtn.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.disabledBackground"));
        forgotpasswordBtn.setFont(new java.awt.Font("Shree Devanagari 714", 0, 13)); // NOI18N
        forgotpasswordBtn.setForeground(new java.awt.Color(0, 0, 0));
        forgotpasswordBtn.setText("Password");
        forgotpasswordBtn.setToolTipText("");
        forgotpasswordBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        forgotpasswordBtn.setBorderPainted(false);
        forgotpasswordBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                forgotpasswordBtnActionPerformed(evt);
            }
        });
        jPanel2.add(forgotpasswordBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 310, 70, 30));

        passwordTxt.setBackground(new java.awt.Color(153, 153, 153));
        passwordTxt.setBorder(null);
        passwordTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordTxtActionPerformed(evt);
            }
        });
        jPanel2.add(passwordTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, 190, -1));

        registerBtn.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.disabledBackground"));
        registerBtn.setFont(new java.awt.Font("Shree Devanagari 714", 0, 13)); // NOI18N
        registerBtn.setForeground(new java.awt.Color(0, 0, 0));
        registerBtn.setText("Register");
        registerBtn.setToolTipText("");
        registerBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        registerBtn.setBorderPainted(false);
        registerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerBtnActionPerformed(evt);
            }
        });
        jPanel2.add(registerBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 350, 70, 30));

        jLabel8.setBackground(new java.awt.Color(0, 0, 0));
        jLabel8.setFont(new java.awt.Font("Shree Devanagari 714", 0, 14)); // NOI18N
        jLabel8.setText("New Account?");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 350, -1, 30));

        jLabel1.setFont(new java.awt.Font("Shree Devanagari 714", 0, 12)); // NOI18N
        jLabel1.setText("Password:");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, -1, -1));

        jLabel2.setFont(new java.awt.Font("Shree Devanagari 714", 0, 12)); // NOI18N
        jLabel2.setText("Username:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 327, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nameTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameTxtActionPerformed

    private void loginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBtnActionPerformed
        // TODO add your handling code here:
        resultLbl.setText("");
         String username = nameTxt.getText();
        String password = passwordTxt.getText();

        
        try {
            /*Establishing connection between page and database */
            Class.forName("com.mysql.cj.jdbc.Driver");
            String url="jdbc:mysql://localhost:3306/resourceinventorymanagement";
            Connection con=DriverManager.getConnection(url,"root","Hari2006");
            /*Checking if application is locked*/
            String attemptcheck = "SELECT * FROM attemptlogin";
                             pstatement = con.prepareStatement(attemptcheck);
            rset = pstatement.executeQuery();
             SimpleDateFormat formatter = new SimpleDateFormat("dd/MM/yyyy HH:mm:ss");
                              Date datess = new Date();  
                             String dates = formatter.format(datess);
            Integer attemptawaiting = 0;
            Integer repeat = 0;
            // checking if current time is past unlocktime if existing.
            while(rset.next()){
                String unlockdate = rset.getString("unlocktime");
                if(dates.compareTo(unlockdate)>0){
                    attemptawaiting++;
                    System.out.println(attemptawaiting);
                }
                repeat++;
                System.out.println(attemptawaiting);
            }
            if(attemptawaiting == repeat){
            if(attempt<5){
                /*Checking if empty username or password is entered*/
        if(password.length()>0){
            if(username.length()>0){
            String sql = "SELECT * FROM admin_table WHERE Username='"+username+"' AND Password='"+password+"';";
            pstatement = con.prepareStatement(sql);
            rset = pstatement.executeQuery();
            

            if (rset.next()) {
                // Successful login
                 /*If username and password match database details, system logs information and sends admin id to all the other tabs of the application*/
                String rno=rset.getString("Userid");
                StreamlinerLog.init();
                // logs info.
            StreamlinerLog.logger.info("AdminID: "+rno+" has logged in");
            //provides userid to all tabs of the application in order for easy logging.
                new home(rno).setVisible(true);
                new changepassword(rno);
                new product(rno);
                new flowtransaction(rno);
                new deletetransaction(rno);
                new deleteproduct(rno);
                new editproduct(rno);
                new edittransaction(rno);
                new transactionlist(rno);
                setVisible(false);
                pstatement.close();
                
            } else {
                // Invalid login
                resultLbl.setText("Invalid Username or Password");
                StreamlinerLog.init();
                // logs info.
            StreamlinerLog.logger.info("Invalid Attempt to Login");
                attempt++;
                if(attempt==5){
                    StreamlinerLog.init();
                    // locks system for 30 minutes if 5 invalid attempts are done simultaneously
            StreamlinerLog.logger.severe("5 Invalid Attempts to Login, Locked for 30 minutes");
                String Adminemail = "donotreplystreamliner@outlook.com";
                Emailalertsend.sendEmail(Adminemail);
                StreamlinerLog.init();
                StreamlinerLog.logger.info("Alert send to Admin E-mail");
            // creating the unlock date.
                              Date date = new Date();  
                             String attemptdate = formatter.format(date);
                             String initdays =attemptdate.substring(0,2);
                             Integer inidays = Integer.parseInt(initdays);
                             String initmonth =attemptdate.substring(3,5);
                             Integer inimonth = Integer.parseInt(initmonth);
                             String inityear =attemptdate.substring(6,10);
                             Integer iniyear = Integer.parseInt(inityear);
                             String minutes=attemptdate.substring(14,16);
                              String seconds=attemptdate.substring(17,19);
                              String hours=attemptdate.substring(11,13);
                            Integer min= Integer.parseInt(minutes);
                            min = min + 30;
                            if(min>=60){
                                Integer newminutes=min-60;
                                String newminute=Integer.toString(newminutes);
                                if(newminutes<10){
                                    newminute="0"+newminute;

                                }
                                Integer hour= Integer.parseInt(hours);
                                hour = hour + 1;
                                String newhour=Integer.toString(hour);
                                if(hour<10){
                                    newhour = "0"+newhour;
                                }
                                if(hour>=24){
                                    hour = hour-24;
                                    newhour= Integer.toString(hour);
                                    if(hour<10){
                                        newhour="0"+hour;
                                    }
                                    inidays = inidays+1;
                                    System.out.println(inidays);
                                    // switchcase scenario for month change.
                                    switch(inimonth){
                                        case 1:
                                            if(inidays>31){
                                                inidays=inidays-31;
                                                inimonth=inimonth+1;
                                            }
                                    break;
                                    case 2:
                                        if(iniyear%4==0){
                                            if(inidays>29){
                                                inidays=inidays-29;
                                                inimonth=inimonth+1;
                                            }

                                        }
                                        else{
                                            if(inidays>28){
                                                inidays=inidays-28;
                                                inimonth=inimonth+1;
                                        }}  
                                    break;
                                    case 3:
                                            if(inidays>31){
                                                inidays=inidays-31;
                                                inimonth=inimonth+1;
                                            }
                                    break;
                                     case 4:
                                            if(inidays>30){
                                                inidays=inidays-30;
                                                inimonth=inimonth+1;
                                            }
                                    break;
                                     case 5:
                                            if(inidays>31){
                                                inidays=inidays-31;
                                                inimonth=inimonth+1;
                                            }
                                    break;
                                     case 6:
                                            if(inidays>30){
                                                inidays=inidays-30;
                                                inimonth=inimonth+1;
                                            }
                                    break;
                                     case 7:
                                            if(inidays>31){
                                                inidays=inidays-31;
                                                inimonth=inimonth+1;
                                            }
                                    break;
                                     case 8:
                                            if(inidays>31){
                                                inidays=inidays-31;
                                                inimonth=inimonth+1;
                                            }
                                    break;
                                     case 9:
                                            if(inidays>30){
                                                inidays=inidays-30;
                                                inimonth=inimonth+1;
                                            }
                                    break;
                                     case 10:
                                            if(inidays>31){
                                                inidays=inidays-31;
                                                inimonth=inimonth+1;
                                            }
                                    break;
                                     case 11:
                                            if(inidays>30){
                                                inidays=inidays-30;
                                                inimonth=inimonth+1;
                                            }
                                    break;
                                     case 12:
                                            if(inidays>31){
                                                inidays=inidays-31;
                                                inimonth=inimonth+1;
                                            }
                                    break; 
                                }
                                    if(inimonth>12){
                                        iniyear=iniyear+1;
                                    }
                                    String finaldays=Integer.toString(inidays);
                                    if(inidays<10){
                                    finaldays="";
                                    finaldays=finaldays.concat("0"+inidays);
                                }

                                    String finaldate=finaldays.concat("/"+inimonth+"/"+iniyear+" "+newhour+":"+newminute+":"+seconds);

                                    String sqltime = "insert into attemptlogin (locktime,unlocktime) values('"+attemptdate+"','"+finaldate+"');";
            statement = con.createStatement();
            statement.executeUpdate(sqltime);
                                    
                                    
                            } else{
                                     String finaldate=initdays.concat("/"+inimonth+"/"+iniyear+" "+newhour+":"+newminute+":"+seconds);
                                    System.out.println(finaldate);
                                    String sqltime = "insert into attemptlogin (locktime,unlocktime) values('"+attemptdate+"','"+finaldate+"');";
            statement = con.createStatement();
            statement.executeUpdate(sqltime);
                                }
                               
                                
                } else{
                            String finaldate=initdays.concat("/"+initmonth+"/"+inityear+" "+hours+":"+min+":"+seconds);
                            System.out.println(finaldate);
                            String sqltime = "insert into attemptlogin (locktime,unlocktime) values('"+attemptdate+"','"+finaldate+"');";
            statement = con.createStatement();
            statement.executeUpdate(sqltime);
                                
                            }
                  
                            
            }con.close();
        }}else{
                resultLbl.setText("Please enter Username/Password");
            }}
        else{
            resultLbl.setText("Please enter Username/Password");
        }}// Checks database and prevents user/staff from logging in.
        else{
            resultLbl.setText("5 Attempts failed. Locked for 30 minutes.");}
            
        }else{
                  resultLbl.setText("5 Attempts failed. Locked for 30 minutes.");   
                  JOptionPane.showMessageDialog(null,"5 Attempts failed, Application locked for 30 minutes.");
                 // catch clause for MySQL, email send and class error. logs errors as well
                    } }catch (SQLException e) {
            JOptionPane.showMessageDialog(null,"Oops!, Something went wrong. Please Restart the Application and try again. Error: Unable to establish connection with database.");
            StreamlinerLog.init();
            StreamlinerLog.logger.severe("Exception :: "+e);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null,"Oops!, Something went wrong. Please Restart the Application and try again. Error: Unable to utilise JDBC driver.");
            StreamlinerLog.init();
            StreamlinerLog.logger.severe("Exception :: "+ex);
        } catch (MessagingException ex) {
            Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
            StreamlinerLog.init();
            StreamlinerLog.logger.severe("Exception :: "+ex);
        }
            
        
    }//GEN-LAST:event_loginBtnActionPerformed

    private void forgotpasswordBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_forgotpasswordBtnActionPerformed
        // TODO add your handling code here:
       new forgotpassword().setVisible(true);
        setVisible(false);
        
    }//GEN-LAST:event_forgotpasswordBtnActionPerformed

    private void nameTxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nameTxtFocusLost
        // TODO add your handling code here:
        
    }//GEN-LAST:event_nameTxtFocusLost

    private void nameTxtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nameTxtFocusGained
        // TODO add your handling code here:
       
    }//GEN-LAST:event_nameTxtFocusGained

    private void passwordTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordTxtActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_passwordTxtActionPerformed

    private void registerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerBtnActionPerformed
        // TODO add your handling code here:
        new register().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_registerBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */

        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton forgotpasswordBtn;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    public static javax.swing.JButton loginBtn;
    private javax.swing.JTextField nameTxt;
    private javax.swing.JPasswordField passwordTxt;
    public static javax.swing.JButton registerBtn;
    private javax.swing.JLabel resultLbl;
    // End of variables declaration//GEN-END:variables
}
